title: A Brit Who Brunches
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7741935
  brandStrength: 0.3125
  lightness: 1
  brandColors:
    - '#DFE1DF'
    - '#16395C'
    - '#B41814'
    - '#889199'
    - '#000417'
  rhythmicContrast: 0.5089605
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: Brit Brunch
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.66028
layout_spectrum: 0.5
