name: Brit Brunch
favicon: null
layout_spectrum: 0.48913
typography_spectrum: 0.66028
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: A Brit Who Brunches
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#DFE1DF'
    - '#16395C'
    - '#B41814'
    - '#889199'
    - '#000417'
  brandStrength: 0.3125
  lightness: null
  saturation: null
  rhythmicContrast: null
purpose: []
