title: a Brit who Brunches
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8620071
  brandStrength: 0
  lightness: 0.7616488
  brandColors: []
  rhythmicContrast: 0.4032258
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Brit Brunch
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7273429087363183
layout_spectrum: 0.77692
